### ISSUE TITLE
add basic reader

### ISSUE THREAD

**Issue by jtauber** [scaife-viewer/scaife-basic#3]

**Comment by rillian** [comment]
I suppose this is what I was looking for. Can you provide some guidance on implementing this?

**Comment by jtauber** [comment]
@rillian you'll want to follow our work on https://github.com/scaife-viewer/readhomer/ rather than here as that's where we're prototyping most of the new stuff for Scaife.

**Comment by rillian** [comment]
Will do. Thanks!
